apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golem-ingress
  labels:
    route53: golem
spec:
  rules:
    - host: "golem.zgamelogic.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: golem
                port:
                  number: 8080
  tls:
    - hosts:
        - "golem.zgamelogic.com"
      secretName: ingress-tls
