apiVersion: v1
kind: ServiceAccount
metadata:
  name: golem-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: golem-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: golem-pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: golem-pod-reader
subjects:
  - kind: ServiceAccount
    name: golem-sa
    namespace: default
